name: Cordova

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    # Run steps on a matrix of 3 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu20.04
          - arch: armv7
            distro: ubuntu20.04

    steps:
      - uses: actions/checkout@v2
            
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}
      
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run commands
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          dockerRunArgs: |
            --volume "${PWD}/bin:/bin"
          
          install: |
            apt update -q -y
            apt install -q -y curl gnupg
            curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
            echo "deb https://deb.nodesource.com/node_14.x focal main" > /etc/apt/sources.list.d/nodesource.list
            apt update -q -y
            apt install -q -y nodejs
          
          # Set an output parameter `uname` for use in subsequent steps
          
          run: |
            npm -v
            echo "Install cordova"
            npm install -g cordova
            echo "Install the dependencies"
            ls
            npm cache verify
            npm install
            echo "Build www"
            npm run build -- --configuration=mobile
            cp build-pipeline-linux.json build.json
            cordova platform add electron@2.0.0
            cordova build electron --no-telemetry
            mkdir -p bin
            pwd
            ls bin/
      
      - name: Publish Snap
        run: |
          FILE=$(ls bin/*.snap)
          for i in $FILE
          do
            snapcraft upload --release=stable $i
          done
