name: Cordova

on:
  tags:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install Node requirements
        run: |
          npm install -g cordova
          npm install
      
      - name: Build the project
        run: |
          npm run build -- --configuration=mobile

      - name: Build linux packages
        run: |
          cp build-linux.json build.json
          cordova platform add electron@2.0.0
          cordova build electron --no-telemetry
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
