name: Cordova-Windows

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install Node requirements
        run: |
          npm install -g windows-build-tools
          npm install -g cordova
          npm install
      
      - name: Build the project
        run: |
          npm run build -- --configuration=mobile

      - name: Build packages
        run: |
          cp build-pipeline-windows.json build.json
          cordova platform add electron@2.0.0
          cordova build electron --no-telemetry
