name: Cordova-Windows

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node requirements
      run: |
        npm install -g cordova
        npm install

    - name: Build the project
      run: |
        npm run build -- --configuration=mobile

    - name: Write build config
      id: write_config
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'build.json'
        encodedString: ${{ secrets.WINDOWS_BUILD_JSON }}
   
    - name: Write pfx cert
      id: write_pfx
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'sign_TemporaryKey.pfx'
        encodedString: ${{ secrets.WINDOWS_BUILD_KEY }}
 
    - name: Build packages
      run: |
        cp ${{ env.JSON_PATH }} build.json
        cp ${{ env.KEY_PATH }} sign_TemporaryKey.pfx    
        cordova platform add electron@2.0.0
        cordova build electron --no-telemetry
        rm build.json
        rm sign_TemporaryKey.pfx
      env:
        JSON_PATH: ${{ steps.write_config.outputs.filePath }}
        KEY_PATH: ${{ steps.write_pfx.outputs.filePath }}

    - uses: actions/upload-artifact@v2
      with:
        name: windows-packages
        path: platforms\electron\build\*.appx
  
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: windows-packages
    
    - name: Test the project
      run: |
        for file in *.appx
        do
          mv -- "$file" "${file// /_}"
        done
    
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@release-1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        releaseId: ${{ needs.create_release.outputs.id }}
        args: '*.appx'
