name: Cordova

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build_job:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    # Run steps on a matrix of 3 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu20.04
          - arch: armv7
            distro: ubuntu20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install Node requirements
        run: |
          npm install -g cordova
          npm install
      
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}
      
      - name: Build the project
        run: |
          npm run build -- --configuration=mobile

      - name: Build linux packages
        run: |
          cp build-pipeline-linux.json build.json
          cordova platform add electron@2.0.0
          cordova build electron --no-telemetry
          mkdir -p bin
          cp ./platforms/electron/build/*.apk bin/
          cp ./platforms/electron/build/*.AppImage bin/
          cp ./platforms/electron/build/*.snap bin/
          pwd
          ls bin/
        env:
          GH_TOKEN: '${{ secrets.GH_TOKEN }}'

      - name: Publish Snap
        run: |
          FILE=$(ls platforms/electron/build/*.snap)
          for i in $FILE
          do
            snapcraft upload --release=stable $i
          done
      
