name: Cordova-Linux

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install Node requirements
        run: |
          sudo apt update -qq
          sudo apt install -y -qq rpm
          npm install -g cordova
          npm install
      
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}
      
      - name: Build the project
        run: |
          npm run build -- --configuration=mobile
      
      - name: Build linux packages
        run: |
          cordova platform add electron@2.0.0
          #Build snap
          cp res/electron/build-pipeline-snap.json build.json
          cordova build electron --no-telemetry --release
          #Build rpm x64
          cp res/electron/build-pipeline-rpm-amd64.json build.json
          cordova build electron --no-telemetry
          #Build rpm arm64
          cp res/electron/build-pipeline-rpm-arm64.json build.json
          cordova build electron --no-telemetry
          #Build other linux packages
          cp res/electron/build-pipeline-linux.json build.json
          cordova build electron --no-telemetry
        env:
          GH_TOKEN: '${{ secrets.GH_TOKEN }}'

      - name: Publish Snap
        run: |
          FILE=$(ls platforms/electron/build/*.snap)
          for i in $FILE
          do
            snapcraft upload --release=stable $i
          done
