name: Cordova-Windows

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node requirements
      run: |
        npm install -g cordova
        npm install

    - name: Build the project
      run: |
        npm run build -- --configuration=mobile
    
    - name: Build packages
      run: |
        echo ${WINDOWS_BUILD_JSON} | base64 -d > build.json
        echo ${WINDOWS_BUILD_KEY} | base64 -d > sign_TemporaryKey.pfx
        cordova platform add electron@2.0.0
        cordova build electron --no-telemetry
      env:
        WINDOWS_BUILD_JSON: ${{ secrets.WINDOWS_BUILD_JSON }}
        WINDOWS_BUILD_KEY: ${{ secrets.WINDOWS_BUILD_KEY }}

    - uses: actions/upload-artifact@v2
      with:
        name: windows-packages
        path: platforms\electron\build\*.appx
  
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: windows-packages
    
    - name: Test the project
      run: |
        for file in *.appx
        do
          mv -- "$file" "${file// /_}"
        done
    
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@release-1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        releaseId: ${{ needs.create_release.outputs.id }}
        args: '*.appx'
