name: Build Dev

on: push

jobs:
  main:
    name: "Build the EW project"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build
      
      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y -qq webp
          npm install
  
      - name: Build the project
        run: |
          make images
          npm run mbuild

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2
      
      - name: Install dependencies
        run: |
          npm install -g cordova
      
      - name: Build packages
        run: |
          cordova platform add electron@^${{ env.electron }}
          cp res/electron/build-snap-dev.json build.json
          cordova build electron --no-telemetry --edge
        env:
          GH_TOKEN: '${{ secrets.GH_TOKEN }}'
          electron: 4.0.0
          SNAPCRAFT_STORE_CREDENTIALS: '${{ secrets.snapcraft_token_edge }}'
      
      - name: Publish Snap
        run: |
          FILE=$(ls platforms/electron/build/*.snap)
          for i in $FILE
          do
            snapcraft upload --release=edge $i
          done
        env:
          SNAPCRAFT_STORE_CREDENTIALS: '${{ secrets.snapcraft_token_edge }}'
        if: ${{ github.ref == 'refs/heads/master' }}
  
