name: Build Dev

on: push

env:
  node: 18
  electron: ${{ env.electron }}

jobs:
  main:
    name: "Build the EW project"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node }}
      
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
      
      - name: Install dependencies
        run: |
          npm install
  
      - name: Build the project
        run: |
          npm run build -- --configuration=mobile

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.snapcraft_token_edge }}
      
      - name: Install dependencies
        run: |
          npm install -g cordova
      
      - name: Build packages
        run: |
          cordova platform add electron@^${{ env.electron }}
          cp res/electron/build-snap-dev.json build.json
          cordova build electron --no-telemetry --edge
        env:
          GH_TOKEN: '${{ secrets.GH_TOKEN }}'
      
      - name: Publish Snap
        run: |
          FILE=$(ls platforms/electron/build/*.snap)
          for i in $FILE
          do
            snapcraft upload --release=edge $i
          done
        if: ${{ github.ref == 'refs/heads/master' }}
  
