name: Release all

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  prepare:
    uses: ./.github/workflows/workflow-release-prepare.yml
    secrets: inherit
    with:
      node: 20
  
  #Android
  package-android:
    uses: ./.github/workflows/workflow-release-android.yml
    secrets: inherit
    needs: prepare
    with:
      android: 12.0.1
      node: 20
