name: Release all

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  prepare:
    uses: ./.github/workflows/workflow-release-prepare.yml
    secrets: inherit
    with:
      node: 22
  
  #Android
  package-android:
    uses: ./.github/workflows/workflow-release-android.yml
    secrets: inherit
    needs: prepare
    with:
      android: 13.0.0
      node: 22

  #Upload ZIP
  zip:
    uses: ./.github/workflows/workflow-release-zip.yml
    secrets: inherit
    needs: prepare
