name: Release all

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  prepare:
    uses: ./.github/workflows/workflow-release-prepare.yml
    secrets: inherit
    with:
      node: 20
  
  #X64 Arch
  package-x64:
    uses: /.github/workflows/workflow-release-linux.yml@master
    secrets: inherit
    needs: prepare
    with:
      electron: 3.1.0
      node: 20
  
  #X86 Arch
  package-x86:
    uses: /.github/workflows/workflow-release-linux-x86.yml@master
    secrets: inherit
    needs: prepare
    with:
      electron: 3.1.0
      node: 20
  
  #arm64 Arch
  package-arm64:
    uses: /.github/workflows/workflow-release-linux-arm64.yml@master
    secrets: inherit
    needs: prepare
    with:
      electron: 3.1.0
      node: 20

  #armhf Arch
  package-armv7l:
    uses: /.github/workflows/workflow-release-linux-armhf.yml@master
    secrets: inherit
    needs: prepare
    with:
      electron: 3.1.0
      node: 20
  
  #Android
  package-android:
    uses: /.github/workflows/workflow-release-android.yml@master
    secrets: inherit
    needs: prepare
    with:
      android: 12.0.1
      node: 20
  
  #Windows
  package-windows:
    uses: /.github/workflows/workflow-release-windows.yml@master
    secrets: inherit
    needs: prepare
    with:
      electron: 3.1.0
      node: 20

  #Mac OS
  package-mac:
    uses: /.github/workflows/workflow-release-linux-mac.yml@master
    secrets: inherit
    needs: prepare
    with:
      electron: 3.1.0
      node: 20
