name: Build all files

on:
  workflow_dispatch:

jobs:
  prepare:
    uses: ./.github/workflows/workflow-release-prepare.yml
    secrets: inherit
    with:
      node: 20
  
  #X64 Arch
  package-x64:
    uses: ./.github/workflows/workflow-release-linux.yml
    secrets: inherit
    needs: prepare
    with:
      electron: 4.0.0
      node: 20
  
  #arm64 Arch
  package-arm64:
    uses: ./.github/workflows/workflow-release-linux-arm64.yml
    secrets: inherit
    needs: prepare
    with:
      electron: 4.0.0
      node: 20

  #armhf Arch
  package-armv7l:
    uses: ./.github/workflows/workflow-release-linux-armhf.yml
    secrets: inherit
    needs: prepare
    with:
      electron: 4.0.0
      node: 20

  #Windows
  package-windows:
    uses: ./.github/workflows/workflow-release-windows.yml
    secrets: inherit
    needs: prepare
    with:
      electron: 4.0.0
      node: 20

  #Mac OS
  package-mac:
    uses: ./.github/workflows/workflow-release-mac.yml
    secrets: inherit
    needs: prepare
    with:
      electron: 4.0.0
      node: 20
