on:
  workflow_call:
    inputs:
      electron:
        required: true
        type: string
      node:
        required: true
        type: string

jobs:
  #Mac OS
  package-mac:
    name: "Build Mac package"
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node }}
      
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build
      
      - name: Install dependencies
        run: |
          npm install -g cordova
          npm install

      - name: Download the project
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: "mobile.zip"
      - name: Extract the project
        run: unzip mobile.zip
      
      - name: Build packages
        run: |
          cp res/electron/build-pipeline-mac.json build.json
          cordova platform add electron@^${{ inputs.electron }}
          cordova build electron --no-telemetry --release
        env:
          GH_TOKEN: '${{ secrets.GH_TOKEN }}'