name: Linux

on:
  workflow_call:
    inputs:
      electron:
        required: true
        type: string
      node:
        required: true
        type: string

jobs:
  #X64 Arch
  package-x64:
    name: "Build x64 packages"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node }}
      
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build
      
      - name: Cache www directory
        uses: actions/cache@v4
        with:
          path: ~/work/Ellas-War/Ellas-War/www
          key: www-${{ runner.GITHUB_RUN_ID }}
      
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2
      
      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y -qq flatpak-builder rpm 
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install flathub org.freedesktop.Platform/x86_64/23.08 -y
          sudo flatpak install flathub org.freedesktop.Sdk/x86_64/23.08 -y
          sudo flatpak install flathub org.electronjs.Electron2.BaseApp/x86_64/23.08 -y
          npm install -g cordova
          npm install
      
      - name: Build packages
        run: |
          cordova platform add electron@^${{ inputs.electron }}
          cp res/electron/build-pipeline-linux-x64.json build.json
          cordova build electron --no-telemetry --release
        env:
          GH_TOKEN: '${{ secrets.GH_TOKEN }}'
          SNAPCRAFT_STORE_CREDENTIALS: '${{ secrets.SNAPCRAFT_TOKEN }}'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64

      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Build snap arm64
        run: |
          docker run --rm \
            -v $WORKSPACE:/ew \
            -v $WORKSPACE/res/electron/build-snap-arm64.json:/ew/build.json \
            -w /ew --platform linux/arm64/v8 \
            --env SNAPCRAFT_STORE_CREDENTIALS=${SNAPCRAFT_STORE_CREDENTIALS} \
            --privileged \
            -t vparanoiaque/cordova-snap sh -c "cordova build electron --no-telemetry"
        env:
          WORKSPACE: '${{ github.workspace }}'
          SNAPCRAFT_STORE_CREDENTIALS: '${{ secrets.SNAPCRAFT_TOKEN }}'
