name: Build Release

on:
  workflow_call:
    inputs:
      node:
        required: true
        type: string

jobs:
  prepare:
    name: "Build the EW project"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node }}
      
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build
      
      - name: Cache www directory
        uses: actions/cache@v4
        with:
          path: ~/work/Ellas-War/Ellas-War/www
          key: www-${{ runner.GITHUB_RUN_ID }}
      
      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y -qq webp
          npm install

      - name: Build the project
        run: |
          make images
          #Build the web version
          npm run wbuild
          zip -r web.zip web
          #Prepare for the apps
          npm run mbuild
          zip -r mobile.zip www

      - name: Upload web zip file to release
        uses: actions/upload-artifact@v4
        with:
          path: /home/runner/work/Ellas-War/Ellas-War/web.zip
          name: web.zip
          compression-level: 0
      - name: Upload mobile zip file to release
        uses: actions/upload-artifact@v4
        with:
          path: /home/runner/work/Ellas-War/Ellas-War/mobile.zip
          name: mobile.zip
          compression-level: 0
